version: '3'

services:
  server:
    environment:
      - PORT=3000
      - TOKEN=$TOKEN
      - SHEET_ID=$SHEET_ID
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-3000}:3000